version: '3.9'
services:
  database:
    image: 'postgres:15.2-alpine'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mikrorepro
    ports:
      - '5435:5432'
    volumes:
      - database:/var/lib/postgresql/dat

volumes:
  database:
    driver: local
